fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.24.0'
    nexus3_rest:
      repo: 'wandenberg/nexus3_rest'
      ref: '3.11.0'
    remote_file:
      repo: 'lwf-remote_file'
      ref: '1.1.3'
  symlinks:
    nexus_proxy: "#{source_dir}"
