fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.24.0'
    nexus_rest:
      repo: 'atlassian-nexus_rest'
      ref: '0.8.0'
    remote_file:
      repo: 'lwf-remote_file'
      ref: '1.1.3'
  symlinks:
    nexus_proxy: "#{source_dir}"
